(()=>{const U="https://azxiopurzajxjksvzvjm.supabase.co",K="sb_publishable_G_WkfZ2z48Zf6ZkVS6o1Fg_htFQWLTZ";
const T={heritage:["#0b3d32","#d8a83e","#fbf8f0","#18312b"],hope:["#6b3f2a","#e3a94b","#fbf6ee","#2f241d"],impact:["#163b5c","#d9a441","#f5f8fb","#1c2b38"],grace:["#4b315e","#c99a5b","#faf7fb","#2d2533"],unity:["#174d4d","#e0a63a","#f4faf9","#193534"],africa:["#533b20","#c98b35","#fbf6ed","#34291e"],minimal:["#1f2937","#8b9a8f","#f8faf9","#202b27"],earth:["#40513b","#b4864b","#f5f4ed","#263126"],royal:["#30245c","#d5b05a","#faf8ff","#29233d"],future:["#123b48","#3cb8a5","#f2fbfa","#193037"]};
function applyTheme(n,a){const t=T[n]||T.heritage,d=document.documentElement;d.style.setProperty("--forest",t[0]);d.style.setProperty("--forest2",t[0]);d.style.setProperty("--f",t[0]);d.style.setProperty("--gold",t[1]);d.style.setProperty("--g",t[1]);d.style.setProperty("--gold2",t[1]);d.style.setProperty("--c",t[2]);d.style.setProperty("--cream",t[2]);d.style.setProperty("--paper","#fff");d.style.setProperty("--ink",t[3]);d.style.setProperty("--m",t[3]);d.style.setProperty("--muted",t[3]);d.style.setProperty("--line","#e6e8e2");document.body.dataset.studioTheme=n||"heritage";document.body.classList.remove("studio-subtle","studio-lift","studio-slide","studio-zoom","studio-float");if(a&&a!=="none")document.body.classList.add("studio-"+a);if(!document.getElementById("studioRuntimeCss")){const s=document.createElement("style");s.id="studioRuntimeCss";s.textContent=`
:root{--studio-accent:var(--gold);--studio-bg:var(--cream);--studio-primary:var(--forest);--studio-text:var(--ink)}
.topbar,.hero,.give{background-color:var(--studio-primary)!important}.btn,.donate{background-color:var(--studio-accent)!important}.k,.kicker,.eyebrow,.foot h4,.arrow{color:var(--studio-accent)!important}
nav{border-color:var(--line)!important}.card,.story,.involve,.trustbox{border-color:var(--line)!important}.section.cream,.cream{background:var(--studio-bg)!important}
h1,.h2,.card h3,.storybody h3,.involve h3,.aboutcopy .h2{color:var(--studio-primary)!important}.aboutcopy,footer{background:var(--studio-primary)!important}
.icon,.round{background:var(--studio-bg)!important;color:var(--studio-primary)!important}
.studio-lift .card:hover,.studio-lift .story:hover,.studio-lift .involve:hover{transform:translateY(-7px)!important}
.studio-subtle .card,.studio-subtle .story,.studio-subtle .involve{transition:opacity .3s,transform .3s,box-shadow .3s}
.studio-slide .card,.studio-slide .story,.studio-slide .involve,.studio-slide .trustitem{animation:studioSlide .5s both}.studio-zoom .card,.studio-zoom .story,.studio-zoom .involve,.studio-zoom .trustitem{animation:studioZoom .45s both}.studio-float .card,.studio-float .story,.studio-float .involve{animation:studioFloat 3s ease-in-out infinite}
@keyframes studioSlide{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}@keyframes studioZoom{from{opacity:0;transform:scale(.97)}to{opacity:1;transform:none}}@keyframes studioFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}`;document.head.appendChild(s)}}
async function getJson(path){const r=await fetch(U+path,{headers:{apikey:K,Authorization:"Bearer "+K,Accept:"application/json"}});if(!r.ok)throw new Error("Studio sync HTTP "+r.status);return r.json()}
function setLogo(url){if(!url)return;document.querySelectorAll(".logo").forEach(e=>{e.style.backgroundImage="url('"+url.replace(/'/g,"%27")+"')";e.style.backgroundSize="cover";e.style.backgroundPosition="center";e.style.color="transparent";e.textContent=""})}
async function load(){try{const settings=await getJson("/rest/v1/site_settings?select=*&id=eq.true&limit=1");const x=settings[0];if(x){applyTheme(x.active_theme,x.animation_preset);if(x.site_title)document.title=x.site_title;if(x.tagline)document.querySelectorAll("[data-site-tagline]").forEach(e=>e.textContent=x.tagline);setLogo(x.logo_url);if(x.favicon_url){let f=document.querySelector('link[rel="icon"]');if(!f){f=document.createElement("link");f.rel="icon";document.head.appendChild(f)}f.href=x.favicon_url}}const page=(location.pathname.split("/").pop().replace(/\.html$/,"")||"home");const rows=await getJson("/rest/v1/site_content?select=section,content_key,content_value,content_type&page=eq."+encodeURIComponent(page));for(const r of rows){const key=r.section+"."+r.content_key;document.querySelectorAll('[data-site-key="'+CSS.escape(key)+'"]').forEach(e=>{if(r.content_type==="image"){if(e.tagName==="IMG")e.src=r.content_value;else e.style.backgroundImage="url('"+r.content_value.replace(/'/g,"%27")+"')"}else if(r.content_type==="url"&&e.tagName==="A")e.href=r.content_value;else e.textContent=r.content_value})}}catch(e){console.warn("Editing Studio sync skipped:",e.message)}}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",load,{once:true});else load()})();